#!/bin/sh

#
#A script to pre-index a given dataset 

# Input:
# 1) data_source_name
# 2) source_version
# 3) organism
# 4) dataset_name
# 5) tool version <kallisto_linux-v0.43.1> default current verion
# 6) tool_name
#

SCRIPT_NAME=`basename $0`
cd `dirname $0`
echo "Running script from `pwd`"

if [ $# -lt 6 ]
then 
  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool-version tool_name"
  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna kallisto_linux-v0.43.1 kallisto"
  exit 1
fi
tool_name=$6

if [ ! -f $tool_name.cfg ]
then
  echo "ERROR: $tool_name.cfg file missing from `pwd`"
  exit 1
fi

source ./$tool_name.cfg

organism=$3
dataset=$4
data_source=$1
source_version=$2
tool_version=$5

tool_index_base=$INDEX_BASE/$tool_version
tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
index_dir=$tool_index_base/$source_version/$organism-$dataset
datasets_fasta_dir=$FASTA_BASE/$source_version/$organism-$dataset

source_config=../../data_sources/$data_source.cfg

log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism-$dataset.$tool_version.log

rm -rf $log
touch $log

echo "*************************************************" | tee -a $log
echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
echo "*************************************************" | tee -a $log
echo "Date:`date`" | tee -a $log
echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 

if [ ! -d $datasets_fasta_dir ]
then
   echo "ERROR: directory $datasets_fasta_dir does not exists" | tee -a $log
   exit 1
fi
if [ ! -f $tool_exec ]
then
   echo "ERROR: $tool_exec executable missing" | tee -a $log
   exit 1
fi
#
# Create index directory if not exists
#
[ ! -d $index_dir ] && mkdir -p $index_dir
if [ ! -d $index_dir ]
then
   echo "ERROR: Failed to create $index_dir"
   exit 1
fi
echo "Tool-version: $tool_version" | tee -a $log
echo "Path to tool exec : $tool_exec" | tee -a $log
echo "Source-version: $source_version" | tee -a $log
echo "Organism: $organism" | tee -a $log
echo "Dataset: $dataset" | tee -a $log
echo "Indexes Directory: $index_dir" | tee -a $log
echo "Dataset Directory: $datasets_fasta_dir" | tee -a $log
source ./$source_config

file_pattern=""

case "$dataset" in
"cdna")
    file_pattern=${cdna}
    ;;
"cds")
    file_pattern=${cds}
    ;;    
"pep")
    file_pattern=${pep}
    ;;
"ncrna")
    file_pattern=${ncrna}
    ;;

"dna")
    file_pattern=${genome}
    ;;
*)
    ;;
esac

FASTA_FILES=`ls $datasets_fasta_dir | grep $file_pattern`
echo "Dataset File pattern: $file_pattern" | tee -a $log
# run index command
reference_in=""
cd $index_dir
echo "Running indexes from `pwd`" | tee -a $log
for target_file  in $FASTA_FILES
do 
   if [ "$reference_in" = "" ]
   then
      reference_in="$datasets_fasta_dir/$target_file"
   else
      reference_in="$reference_in,$datasets_fasta_dir/$target_file"
   fi
done

bt2_base="$tool_name-$data_source-$dataset"
index_cmd="$tool_exec index -i $bt2_base.idx $reference_in"
echo "Dataset file: $reference_in" | tee -a $log
echo "Cmd: $index_cmd" | tee -a $log
$index_cmd 2>&1 | tee -a $log
echo "Program Complete" | tee -a $log
exit 0
