#!/bin/sh

#
#A script to align reads to the spcified index
# created under tool-version/data_source-version/organism-dataset

# Input:
# 1) data_source_name
# 2) source_version
# 3) organism
# 4) dataset_name
# 5) tool version <hisat2-2.1.0> default current verion
# 6) tool_name
#

SCRIPT_NAME=`basename $0`
cd `dirname $0`
echo "Running script from `pwd`"

if [ $# -lt 7 ]
then 
  echo "Usage: ./$SCRIPT_NAME  source source-version organism dataset tool-version tool_name reads.fa"
  echo "Example: ./$SCRIPT_NAME ensembl ensembl-91 danio_rerio cdna hisat2-2.1.0 hisat2 path2/read"
  exit 1
fi
#Check that bwa.cfg exists 
tool_name=$6

if [ ! -f $tool_name.cfg ]
then
  echo "ERROR: $tool_name.cfg file missing from `pwd`"
  exit 1
fi

source ./$tool_name.cfg

organism=$3
dataset=$4
data_source=$1
source_version=$2
tool_version=$5
reads_file=$7

tool_index_base=$INDEX_BASE/$tool_version
tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_EXEC
index_dir=$tool_index_base/$data_source/$source_version/$organism-$dataset

log=$LOGS_BASE/$SCRIPT_NAME.$data_source.$source_version.$organism-$dataset.$tool_version.log

rm -rf $log
touch $log

echo "*************************************************" | tee -a $log
echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
echo "*************************************************" | tee -a $log
echo "Date:`date`" | tee -a $log
echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 

if [ ! -d $index_dir ]
then
   echo "ERROR: Index directory $index_dir does not exists" | tee -a $log
   exit 1
fi
if [ ! -f $tool_exec ]
then
   echo "ERROR: $tool_exec executable missing" | tee -a $log
   exit 1
fi
echo "Tool-version: $tool_version" | tee -a $log
echo "Path to tool exec : $tool_exec" | tee -a $log
echo "Source-version: $source_version" | tee -a $log
echo "Organism: $organism" | tee -a $log
echo "Dataset: $dataset" | tee -a $log
echo "Input Reads: $reads_file" | tee -a $log
echo "Indexes Directory: $index_dir" | tee -a $log

cd $index_dir
echo "Running alignment from `pwd`" | tee -a $log

read_file=`basename $reads_file`

bt2_base="$tool_name-$data_source-$dataset"
index_cmd="$tool_exec -f -x $bt2_base -U $reads_file -S $bt2_base.$read_file.sam"
echo "Output Sam File : $bt2_base.$read_file.sam" | tee -a $log
echo "Cmd: $index_cmd" | tee -a $log
$index_cmd 2>&1 | tee -a $log

[ $? -ne 0 ] && exit 1

echo "Program Complete" | tee -a $log
exit 0
