#!/bin/sh

#
#A script to pre-index a given dataset 
# Without using the isoform or gtf options
# Example:
# rsem-prepare-reference   path2/mm9.fasta  reference_name
#

# Input:
# 1) data_source_name
# 2) source_version
# 3) organism
# 4) dataset_name
# 5) tool name
# 6) tool version default current verion
#

SCRIPT_NAME=`basename $0`
cd `dirname $0`
echo "Running script from `pwd`"

WORKING_DIR=`pwd`

if [ $# -lt 6 ]
then 
  echo "Usage: ./$SCRIPT_NAME dataset-version  organism dataset \
        path2/reference_fasta_file index_dir index_prefix [polyA]"
  echo "Example: ./$SCRIPT_NAME release-94  mus_musculus cdna \
 /data/scratch/ensembl-94/mus_musculus-cdna/Mus_musculus.GRCm38.cdna.all.fa \
 /data/transformed/RSEM-v1.3.0/ensembl-94/mus_musculus-cdna transcriptome
        "
  exit 1
fi

tool_name=rsem
tool_config=$tool_name.cfg
main_config=Configuration.cfg
##
if [ ! -f ../../$main_config ]
then
  echo "ERROR: ../../$main_config file missing"
  exit 1 
fi
source ./../../$main_config
if [ ! -f $tool_config ]
then
  echo "ERROR: $tool_config file missing from `pwd`"
  exit 1
fi
##Set this tool's specific variables
#
source ./$tool_config

source_version=$1
organism=$2
dataset=$3
reference_file=$4
index_dir=$5
index_file_prefix=$6
polyA=""
tool_version=$TOOL_VERSION
[ $# -gt 6 ] && polyA="--polyA"

tool_index_base=$INDEX_BASE/$tool_version
tool_exec=$PACKAGE_INSTALL_BASE/$tool_version/$TOOL_INDEX_EXEC
if [ ! -f $tool_exec ]
then
   echo "ERROR: $tool_exec executable missing" | tee -a $log
   exit 1
fi
#If this dataset has already been indexed continue
if [ -d $index_dir ]
then
   [ "$(ls -A $index_dir)" ] && mv $index_dir $index_dir.archive
fi
#
# Create index directory if not exists
#
[ ! -d $index_dir ] && mkdir -p $index_dir
if [ ! -d $index_dir ]
then
   echo "ERROR: Failed to create $index_dir"
   exit 1
fi

log=$LOGS_BASE/$SCRIPT_NAME.$source_version.$organism.$dataset.$tool_version.log

rm -rf $log
touch $log
echo "*************************************************" | tee -a $log
echo "" | tee -a $log
echo "Generating $tool_version indexes for $source_version $organism's $dataset"  | tee -a $log
echo "" | tee -a $log
echo "*************************************************" | tee -a $log
echo "" | tee -a $log
echo "ORGANIZATION:$ORGANIZATION" | tee -a $log 
echo "" | tee -a $log
echo "Date:`date`" | tee -a $log
echo "Tool-version: $tool_version" | tee -a $log
echo "Path to tool exec : $tool_exec" | tee -a $log
echo "Running indexer from `pwd`" | tee -a $log
echo "Organism: $organism" | tee -a $log
echo "Dataset: $dataset" | tee -a $log
echo "Indexes Directory: $index_dir" | tee -a $log
echo "Indexes File Prefix: $index_file_prefix" | tee -a $log
echo "Refence Data Source version: $source_version" | tee -a $log
echo "Transcript gtf Input file: $transcript_gtf_file" | tee -a $log
echo "Reference fasta file: $reference_file" | tee -a $log

index_cmd="$tool_exec $polyA $reference_file $index_dir/$index_file_prefix"
echo " -------------------------- " | tee -a $log
echo " " | tee -a $log
echo "Indexer Cmd: $index_cmd" | tee -a $log
echo " " | tee -a $log
echo "=== `basename $tool_exec`'s Logs start Here ===" | tee -a $log
$index_cmd 2>&1 | tee -a $log
echo "=== `basename $tool_exec`'s Logs end Here ===" | tee -a $log
echo "Program Complete" | tee -a $log
exit 0
